# Site settings
title: OpenSource разработка от MasterKod'а
email: i@rootooz.com
description: > # this means to ignore newlines until "baseurl:"
    Персональный блог с рецептами по Ruby on Rails, Linux, Console и не только
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rootooz.com" # the base hostname & protocol for your site
twitter_username: rootooz
github_username:  rootooz

# Build settings
markdown: kramdown
excerpt_separator: '<!--more-->'

gems:
  - jekyll-sitemap
#  - jekyll-coffeescript
#  - jekyll-paginate
