# Site settings
title: Записная книжка
email: ceo@rostio.ru
description: > # this means to ignore newlines until "baseurl:"
    Персональный блог с рецептами по Yii, Yii2, Ruby on Rails, Linux, Console
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rostio.ru" # the base hostname & protocol for your site
twitter_username: rootooz
github_username:  rootooz

# Build settings
markdown: kramdown
